; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = vision_master_e290

[env:vision_master_e290]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.8.134

build_flags =
  -D Vision_Master_E290
  -D HELTEC_BOARD=37
  -D LoRaWAN_DEBUG_LEVEL=0
  -D SLOW_CLK_TPYE=0
  -D GPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT

lib_extra_dirs =
  C:/Users/Jason/Documents/Arduino/libraries

lib_deps =
  adafruit/Adafruit LSM6DS
  bblanchon/ArduinoJson
  sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library

lib_ignore =
  WiFiNINA
  ArduinoHttpClient
  WiFi101

[env:vision_master_e290_usb]
extends = env:vision_master_e290
upload_protocol = esptool
upload_port = COM9