[platformio]
build_dir = C:/Users/Jason/AppData/Local/Temp/scuba-pio-build

[env:vision_master_e290]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM4
monitor_port = COM4
board_build.variant = heltec_vision_master_e290
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
lib_extra_dirs = C:/Users/Jason/Documents/Arduino/libraries
lib_ldf_mode = deep+
lib_ignore =
  ArduinoHttpClient
  Arduino_SpiNINA
  WiFi101
  WiFiNINA
build_src_filter =
  +<main.cpp>
build_flags =
  -IC:/Users/Jason/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DREGION_US915
  -DMCU_ESP32_S3
  -DHELTEC_BOARD=37
  -DHELTEC_VISION_MASTER_E290
  -DVision_Master_E290=true
  -DSLOW_CLK_TPYE=0
  -DRADIO_CHIP_SX1262
  -DLoRaWAN_DEBUG_LEVEL=0
  -DACTIVE_REGION=LORAMAC_REGION_US915
  -DLORAWAN_PREAMBLE_LENGTH=8
  -DLORAWAN_DEVEUI_AUTO=0
